# Generated by Django 2.2.1 on 2019-05-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Domicilio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('talla', models.CharField(choices=[('S', 'CHICA'), ('M', 'MEDIANA'), ('L', 'GRANDE')], default='S', max_length=30)),
                ('foto', models.URLField(default='')),
            ],
        ),
    ]
