# Generated by Django 2.2.1 on 2019-05-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='costo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
